### ISSUE TITLE
Missing runtime dependency Astrolabe

### ISSUE THREAD

**Issue by tpbowden** [sds/slim-lint#22] opened 2016-01-15 10:19 UTC
This gem has a runtime dependency on the gem Astrolabe which is used in the file [ruby_parser.rb#L1](https://github.com/sds/slim-lint/blob/master/lib/slim_lint/ruby_parser.rb#L1).

Previously this dependency was brought in through Rubocop, but as of Rubocop-0.36.0 this is no longer the case. Adding it as a runtime dependency should fix this issue (or lock the version of Rubocop to 0.35.1).

The error caused by this missing dependency is `LoadError: cannot load such file -- astrolabe/builder`

**Comment by sds** [comment] 2016-01-19 04:09
Duplicate of #21.

**Closed by sds** 2016-01-19 04:09 UTC
Labels: duplicate
